### ISSUE TITLE
Compiling plugin under Windows

### ISSUE THREAD

**Issue by Krukosz** [EionRobb/purple-gowhatsapp#1]
Hi,

I saw that you've successfully compiled .dll that worked. Now i'm receiving errors of bad JSON during verification.

How did you installed developer headers of pidgin on Windows. I followed the Pidgin wiki, but no good result.
I also featured my problem in original repository, but now issue is closed.

[Original issue](https://github.com/hoehermann/purple-gowhatsapp/issues/21)

**Comment by EionRobb** [comment]
Yep, just following the instructions using the [BuildingWinPidgin](https://developer.pidgin.im/wiki/BuildingWinPidgin) wiki page

What errors are you getting with building the plugin?

**Comment by EionRobb** [comment]
Oh, are you building using `make -f Makefile.mingw`?  You will need to tweak the paths in Makefile.mingw to the pidgin-2.x.y folder in your cygwin folder as I intentionally compile against an older version of Pidgin for backwards-compat.  But you'll need to make sure you've compiled Pidgin first.

**Comment by Krukosz** [comment]
I used the [pidgin-windev](https://github.com/DigitalDJ/pidgin-windev). I successfully compiled pidgin, but I receive errors during creating installer:

`make -f Makefile.mingw installers`

**Comment by EionRobb** [comment]
You don't need to be able to build the installer, just `make -f Makefile.mingw` in the Pidgin dir is enough to be able to compile Pidgin plugins on Windows

After changing the Makefile.mingw in the purple-gowhatsapp plugin to point to your freshly compiled pidgin folder, what errors are you getting?

**Comment by Krukosz** [comment]
I tried this installation on different machine that now i'm using. I'll install everything once again on current machine and will back to you.

Thank you

**Comment by Krukosz** [comment]
For now it's my worst programming-related experience so far.
Could you please tell me how to install mingw, because its libraries are in different versions and cc1.exe doesn't see them. 
For example i have libmpc-3.dll instead of libmpc-2.dll
I use mingw32 from official website.

**EDIT:** I downloaded missing libraries at my own, now I'm facing compilation problems described [here](https://github.com/hoehermann/purple-gowhatsapp/issues/23)

**Comment by EionRobb** [comment]
cc1.exe isn't the gcc that mingw uses, you might be compiling with cygwin's compiler instead.  The Makefile.mingw refers to the mingw gcc that's provided when following the BuildingWinPidgin wiki page

**Comment by Krukosz** [comment]
The makefile.mingw provided with plugin uses golang, which afaik is not supported by cygwin.

**Comment by EionRobb** [comment]
Oh, I used https://golang.org/dl/ to install the Go binaries
