### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by rojmiller** [EionRobb/purple-gowhatsapp#4]
The plugin for Pidgin on Windows stopped working today. The error message is:

error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

**Comment by b2cbd** [comment]
@rojmiller  same here.

@EionRobb any chances to get a compiled DLL based on the latest commits by @hoehermann ?

**Comment by EionRobb** [comment]
Whoops, I forgot this repo still exists. Happy to build a new dll

**Comment by b2cbd** [comment]
@EionRobb  Thanks! Waiting for it...

**Comment by EionRobb** [comment]
https://github.com/hoehermann/purple-gowhatsapp/files/4449243/libgowhatsapp.zip

**Comment by b2cbd** [comment]
@EionRobb Thanks, it works.

**Comment by rojmiller** [comment]
Works for me too

**Comment by b2cbd** [comment]
again it broke. Solved [here](https://github.com/hoehermann/purple-gowhatsapp/issues/50).  

@EionRobb  May we get a compiled Dll? :)

**Comment by EionRobb** [comment]
https://github.com/hoehermann/purple-gowhatsapp/files/4514829/libgowhatsapp.zip
